---
title: "Prueba de WEB"
author: "José Antonio Burgos"
date: "17/11/2020"
output: html_document
---

```{r}
library(readxl)
```

## Descarga desde la web de la base de datos

```{r}
oneb<-"https://www.one.gob.do/Multimedia/Download?ObjId=102031" # Link de la web
oneb2<-file.path("~","local_Download?ObjId=102031") # Ubicacion 
download.file(oneb,oneb2) # descargando al directirio de trabajo 
onet<-read_excel(oneb2,col_names = c("Provincia",  # cargando la base de datos 
                                     "2001",   # Nombrando las columnas  
                                     "2002",
                                     "2003",
                                     "2004",
                                     "2005",
                                     "2006",
                                     "2007",
                                     "2008",
                                     "2009",
                                     "2010",
                                     "2011",
                                     "2012",
                                     "2013",
                                     "2014",
                                     "2015",
                                     "2016",
                                     "2017",
                                     "2018",
                                     "2019"))
```


### Manipulando la base de datos 
```{r}
onett<-onet[c(4:40),]
onett<-onett[-c(2:6),]
```

